import {VideoProps} from './theme';

// Default props for the Studio / a render without --props. Mirrors public/demo/props.json.
export const demoProps: VideoProps = {
  aspect: '9:16',
  width: 1080,
  height: 1920,
  fps: 30,
  durationSec: 13,
  scenes: [
    {index: 1, start: 0, end: 2.5, kind: 'image', src: 'demo/scene-1.jpg', fit: 'cover', kenBurns: 'in'},
    {
      index: 2,
      start: 2.5,
      end: 8,
      kind: 'video',
      src: 'demo/clip-1.mp4',
      fit: 'cover',
      kenBurns: 'in',
      loop: true,
      srcDurationSec: 5,
    },
    {index: 3, start: 8, end: 10.5, kind: 'image', src: 'demo/scene-3.jpg', fit: 'cover', kenBurns: 'left'},
  ],
  words: [
    {s: 0.4, e: 0.75, w: 'Cats'},
    {s: 0.8, e: 1.1, w: 'sleep'},
    {s: 1.15, e: 1.4, w: '16'},
    {s: 1.45, e: 1.9, w: 'hours'},
    {s: 2.5, e: 2.7, w: 'a'},
    {s: 2.75, e: 3.2, w: 'day'},
    {s: 4.2, e: 4.5, w: 'and'},
    {s: 4.55, e: 4.9, w: 'still'},
    {s: 5.0, e: 5.5, w: 'earn'},
    {s: 5.6, e: 6.2, w: '$1000'},
    {s: 7.0, e: 7.3, w: 'from'},
    {s: 7.35, e: 7.8, w: 'every'},
    {s: 7.9, e: 8.5, w: 'video'},
    {s: 9.0, e: 9.4, w: 'you'},
    {s: 9.45, e: 10.2, w: 'post'},
  ],
  captions: {
    enabled: true,
    preset: 'karaoke',
    position: 'bottom',
    fontSize: 78,
    maxWords: 3,
    uppercase: true,
    accent: '#10b981',
    emphasis: '#fbbf24',
    textColor: '#ffffff',
    strokeColor: '#0a0e0c',
  },
  title: {text: 'Why cats sleep 16 h', durSec: 0},
  outro: {text: 'Follow for more', sub: '@cashcannon', durSec: 2.5},
  transition: 'fade',
  progressBar: true,
  watermark: {text: 'made with CashCannon'},
  theme: {accent: '#10b981', bg: '#0a0e0c', font: 'Onest'},
};
